### ISSUE TITLE
find out whether it works to retrofit compute HA to existing cloud with controller HA

### ISSUE THREAD

**Issue by aspiers** [SUSE/compute-ha-training#1]
This would avoid the need to waste time redeploying the whole cloud after the controller HA stuff on Wed morning.

It should work fine (it used to) but we would need to test before the lab.  @vuntz I don't suppose you tested this recently?  @dguitarbite this is relevant to you too.

**Comment by dguitarbite** [comment]
Hi Adam,
I'm travelling back to Nue and will reply today night. You could send me
more of these things so I can pre-prepare. We should also have time from
Monday afternoon to Wed morning to hack. I don't have internet on the way
back but I should be online by 10:00 pm CEST.

I am on a shirt weekend break over at my friends on the other end of
Germany.

Regards,
Pranav

**Comment by vuntz** [comment]
I guess you mean: "add compute HA after having initially deployed HA"? I think I tried that and it worked.

**Comment by aspiers** [comment]
Thanks, that's what I expected too but wanted to make sure.  If possible we should test with Pranav's setup though, as a lot hinges on the success of that.

**Comment by aspiers** [comment]
It works!
